0.6/Dockerfile
The latest version of Alpine resolves the issue with using `ping` as non-root
user.
Additional information found here:
http://alpinelinux.org/posts/Alpine-3.4.0-released.html
fixes: #17
=> Updates Alpine to 3.4

0.6/docker-entrypoint.sh
Fixes #20 
There's a decision to be made here.  I've gone with a conservative approach where we only chown `/consul/data` and `/consul/config` if they are owned by container's `root`.  This fixes the case where the host mount location is owned by root or dynamically created by `docker run` when run as `root`.
There are two other options:
1. Always chown.
2. Never chown and instead print a BIG FAT WARNING and exit.
I verified this patch by running this as `root` in `/root` without the patch.  I received the permission denied error as in #20.  I then built with the patch applied and the container started.
=> Chown data and config before gosu

0.6/Dockerfile
The reason for adding Curl is so that tools like https://github.com/AcalephStorage/consul-alerts can work off the bat.
=> Updating Dockerfile to include curl

0.6/Dockerfile, 0.6/docker-entrypoint.sh
This takes #24 and makes it opt-in via an environment variable.
Closes #24 
Closes #15 
/cc @jefferai
=> Allows for binding privileged ports as consul user.

0.X/docker-entrypoint.sh
A very minor change:
Instead of checking if the directory is owned by root, check if it's _not_ owned by consul before changing it.
This could prevent future problems if Alpine changes or is swapped for something else and the UID ends up not being 100.
=> File ownership based on consul user's id

0.X/Dockerfile
Bumped Consul and and alpine to latest stable.
=> Bump Consul to release version 0.8.0, bump alpine to 3.5 (latest)

0.X/Dockerfile
Noticed in my log that 1.0.7 was released. Is this all that is needed for the docker container to get updated?
=> Bump to 1.0.7

0.X/Dockerfile
Fixes #67
@slackpad any idea what the value of `GOARM` was when building the `consul_1.0.3_linux_arm.zip` binary that's on https://releases.hashicorp.com/consul/1.0.3/ ?
(or anyone with an `arm32v6` Raspberry Pi 1 or Zero willing to try running that binary for me and tell me if it errors?)
=> Add multiarch support based on available release binaries

0.X/Dockerfile
The image did not include `/etc/nsswitch.conf`, and so hostname resolution was using DNS before checking `/etc/hosts`. This commit fixes that.
See https://github.com/hashicorp/docker-consul/issues/94
=> Added /etc/nsswitch.conf file so container's hosts file is respected by Consul - fixes #94

0.X/Dockerfile
Right now the GPG key is received over plain tcp + HTTP. This will force the GPG command to receive the key over HKPS which uses TLS.
=> Use HKPS for receiving GPG key over TLS

0.X/Dockerfile
Fixes: #17 
`/bin/ping` in alpine is normally a symlink to `/bin/busybox`. On other distros `/bin/ping` is a setuid binary to allow ICMP sockets to work for regular users.
So there were 3 options:
1 - `chmod u+s /bin/ping`
2 - Install a ping binary not associated with busybox
3 - Require users to configure the host linux to allow GID 1000 the ability to ping (sysctl net.ipv4.ping_group_range)
Number 1 would be terribly insecure as it actually makes the entire `/bin/busybox` binary setuid and almost every command in `/bin` is actually just a symlink to `/bin/busybox`. Number 3 puts the burden of configuration on the user and isn't a wonderful UX. Number 2 however only has the downsides of including a few extra binaries in the image. The size becomes a little larger but not by much. …
=> Fix issue with ping not working within script checks

0.X/Dockerfile
We'll reference these specific sha's elsewhere. This should not be squashed.
We released [backports](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/consul-tool/kmGKTj3YxUg) for a security incident and need specific shas to reference for these versions in order to update the official docker-images manifest.
=> Backport Versions

0.X/docker-entrypoint.sh
This allows the container to be run in a mode where we don't drop to the consul user and do not perform chown on the data/conf directories and do not ever try to enable privileged port binding.
Essentially using the env var opts you out of all the permission type things and you now need to manage it yourself.
It can now be run like:
`docker run -e CONSUL_DISABLE_PERM_MGMT= consul:latest`
Without specifying the new environment variable the previous behavior will be used.
The main use case for this is around executing the container as non-root. The user running the container will then need to ensure that the permissions on the data directory and the config directory allow the user running the container access.
=> Add capability to disable user and permission management with env var

0.X/docker-entrypoint.sh
As there are variables defined for consul data and config directories, there is no need to use hard-coded values in correcting ownership of these directories.
=> Remove hardcode for consul dirs

0.X/Dockerfile
Sometimes the gpg directory cannot be removed and this should take care
of it by killing all the running gpg deamons. This is what it looks like
if it fails:
```
(23/23) Purging sqlite-libs (3.28.0-r3)
Executing busybox-1.29.3-r10.trigger
OK: 9 MiB in 25 packages
+ rm -rf /root/.gnupg
rm: can't remove '/root/.gnupg/S.gpg-agent.browser': No such file or directory
Removing intermediate container aa9b1ae8718f
```
And this is where it happened:
https://github.com/docker-library/official-images/runs/663648218.
Credit to @tianon:
https://github.com/docker-library/official-images/pull/7976#issuecomment-626748203.
=> Stop gpg deamons

0.X/Dockerfile
Fixes #147
Also replace the MAINTAINER instruction with a label, as suggested by
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
Tested with `docker build; docker run`, and it worked for linux/amd64 at least. How else should I test this?
=> Update alpine version

0.X/Dockerfile
Reverts hashicorp/docker-consul#157 to avoid rejection in https://github.com/docker-library/official-images/pull/9041#issuecomment-723369880
=> Revert "switch to hashicorp docker mirror"

0.X/Dockerfile
While generally you would use ARGs by passing them in with `--build-arg`, the Docker official images does not support this so we will just use it as a variable to set the version and then use it to set it in the environment for `CONSUL_VERSION` and the `consul.version` label
=> use a variable to specify consul version env var and label

0.X/Dockerfile
https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys pre-defines `org.opencontainers.image.version` to use for versioning. consul-enterprise pre-release versions do not adhere quite to semver but the wording is `MAY` so this should suffice.
Outside of the versioning we do ourselves, if we want to keep the docker tag consistent with `org.opencontainers.image.version` and in line with semver, this is currently not possible due to https://github.com/docker/distribution/issues/1201 where docker tags cannot take `+`.
=> use oci spec pre-defined key for version

0.X/Dockerfile
This adopts the new HashiCorp PGP key, as described at https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 and https://hashicorp.com/security.
Addresses https://github.com/hashicorp/docker-consul/issues/165.
=> adopt new HashiCorp PGP key

0.X/docker-entrypoint.sh
This change would allow users to specify the values for `CONSUL_BIND` and `CONSUL_CLIENT` via the environment variables.  This allows users to utilize more complex, dynamic auto-configuration for the binding interfaces via the supported [go-sockaddr template configuration](https://pkg.go.dev/github.com/hashicorp/go-sockaddr/template) as documented [here](https://www.consul.io/docs/agent/options#_bind).
Such an example might be:
```
CONSUL_BIND='-bind {{ GetPrivateInterface }}'
```
or
```
CONSUL_BIND='-bind {{ GetAllInterfaces | include "name" "^eth" | include "flags" "forwardable|up" | attr "address" }}'
```
An important use case for this functionality is when running Consul on AWS ECS/Fargate. Fargate promises that containers will have a routable IP address in their VPC subnet, but it …
=> entrypoint: Don't clear CONSUL_BIND and CONSUL_CLIENT envvars at start

0.X/Dockerfile
As defined in https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#pre-defined-annotation-keys and requested in https://github.com/docker-library/official-images/pull/10804#issuecomment-907539632
Followed the backwards compatibility guide at https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#back-compatibility-with-label-schema for migration.
=> migrate to OCI spec labels

0.X/docker-entrypoint.sh
This patch allow to set UID/GID via environments. This allow to use CONSUL_ALLOW_PRIVILEGED_PORTS and starting consul with uid/gid that passed for example from docker-compose. I've manage users via puppet outside of containers and need to start consul with UID/GID from puppet. Also I've added config and data dir configuration from environment and reindent docker-entrypoint.sh, because mix from spaces and tabs does not a good idea.
=> Remove some hardcodes

0.X/Dockerfile
This supersedes #123 and makes the same change on an up-to-date base. 
This enables users to set timezone by doing:
```
docker run -e "TZ=Europe/Moscow" --rm consul date
```
=> Add suppoort for setting timezone

0.X/Dockerfile
You could argue that this should be latest, but it matches what our unofficial images get from consul/Dockerfile.
=> Update Docker to use alpine:3.15

ubi/Dockerfile
Bumping for posterity, by the next core release we will likely be using the Dockerfile from https://github.com/hashicorp/consul/pull/13232/files
=> UBI Image: bump to ubi-minimal:8.6
